export const UPLOAD_FILE_FOR_MATCH_REQUEST  = 'UPLOAD_FILE_FOR_MATCH_REQUEST'
export const UPLOAD_FILE_FOR_MATCH_SUCCESS  = 'UPLOAD_FILE_FOR_MATCH_SUCCESS'
export const UPLOAD_FILE_FOR_MATCH_FAILED  = 'UPLOAD_FILE_FOR_MATCH_FAILED'
export const UPLOAD_FILE_FOR_MATCH_CLEAR  = 'UPLOAD_FILE_FOR_MATCH_CLEAR'

export const GET_RESULTS_REQUEST  = 'GET_RESULTS_REQUEST'
export const GET_RESULTS_SUCCESS  = 'GET_RESULTS_SUCCESS'
export const GET_RESULTS_FAILED  = 'GET_RESULTS_FAILED'
export const GET_RESULTS_CLEAR  = 'GET_RESULTS_CLEAR'

export const SAVE_RESULT_REQUEST  = 'SAVE_RESULT_REQUEST'
export const SAVE_RESULT_SUCCESS  = 'SAVE_RESULT_SUCCESS'
export const SAVE_RESULT_FAILED  = 'SAVE_RESULT_FAILED'
export const SAVE_RESULT_CLEAR  = 'SAVE_RESULT_CLEAR'

export const CLEAR_DATABASE_REQUEST  = 'CLEAR_DATABASE_REQUEST'
export const CLEAR_DATABASE_SUCCESS  = 'CLEAR_DATABASE_SUCCESS'
export const CLEAR_DATABASE_FAILED  = 'CLEAR_DATABASE_FAILED'

export const REBUILD_NOMENCLATURE_STORE  = 'REBUILD_NOMENCLATURE_STORE'
